#########################################################################
#                                                                       #
#                                 OCaml                                 #
#                                                                       #
#              Anil Madhavapeddy, OCaml Labs                            #
#                                                                       #
#   Copyright 2014 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the Q Public License version 1.0.                #
#                                                                       #
#########################################################################

language: c
script: bash -ex .travis-ci.sh
env:
   - XARCH=i386
